// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTemplateList = "template_lists"

// TemplateList mapped from table <template_lists>
type TemplateList struct {
	ID           int64  `gorm:"column:id;type:int(32);primaryKey;autoIncrement:true" json:"id,string"`
	Name         string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	SendChannel  string `gorm:"column:send_channel;type:varchar(255);not null" json:"send_channel"`
	TemplateType string `gorm:"column:template_type;type:varchar(255);not null" json:"template_type"`
	MessageType  string `gorm:"column:message_type;type:varchar(255);not null" json:"message_type"`
	CreateUser   string `gorm:"column:create_user;type:varchar(255);not null" json:"create_user"`
	ReceiverType string `gorm:"column:receiver_type;type:varchar(255);not null" json:"receiver_type"`
	Deleted      int64  `gorm:"column:deleted;type:int(1) unsigned zerofill;not null" json:"deleted"`
}

// TableName TemplateList's table name
func (*TemplateList) TableName() string {
	return TableNameTemplateList
}
