// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTemplate = "templates"

// Template mapped from table <templates>
type Template struct {
	ID           int64  `gorm:"column:id;type:int(32);primaryKey;autoIncrement:true" json:"id,string"`
	Name         string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	BusinessName string `gorm:"column:business_name;type:varchar(255)" json:"business_name"`
	ReceiverType string `gorm:"column:receiver_type;type:varchar(255);not null" json:"receiver_type"`
	MessageType  string `gorm:"column:message_type;type:varchar(255);not null" json:"message_type"`
	ShieldType   string `gorm:"column:shield_type;type:varchar(255);not null" json:"shield_type"`
	TemplateType string `gorm:"column:template_type;type:varchar(255);not null" json:"template_type"`
	SendChannel  string `gorm:"column:send_channel;type:varchar(255);not null" json:"send_channel"`
	Deleted      int64  `gorm:"column:deleted;type:int(1) unsigned zerofill;not null" json:"deleted"`
}

// TableName Template's table name
func (*Template) TableName() string {
	return TableNameTemplate
}
